"""empty message

Revision ID: 57474c651d81
Revises: 
Create Date: 2025-05-25 22:06:57.704685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57474c651d81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreProducto', sa.String(length=50), nullable=True),
    sa.Column('descripcionProducto', sa.String(length=50), nullable=True),
    sa.Column('unidadesProducto', sa.Integer(), nullable=True),
    sa.Column('costoProducto', sa.Float(), nullable=True),
    sa.Column('precioProducto', sa.Float(), nullable=True),
    sa.Column('categoriaProducto', sa.String(length=50), nullable=True),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.Column('nombreUsuario', sa.String(length=50), nullable=True),
    sa.Column('descripcionAccion', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=50), nullable=True),
    sa.Column('unidades', sa.Integer(), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('contrasenha', sa.String(length=50), nullable=True),
    sa.Column('administrador', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('producto')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
